package prefixed

var prefixReplacements = map[string]string{
	"runtime":                                         "registry",
	"runtime/debug":                                   "runtime",
	"runtime/messagehandler":                          "message-handler",
	"runtime/prereqs":                                 "runtime-prereqs",
	"cmd/beacon-chain":                                "main",
	"cmd/client-stats":                                "main",
	"cmd/silactl/p2p":                                "silactl-p2p",
	"cmd/silactl/testnet":                            "genesis",
	"cmd/validator/slashing-protection":               "historycmd",
	"cmd/validator":                                   "main",
	"cmd":                                             "node",
	"beacon-chain/cache/depositsnapshot":              "cache",
	"beacon-chain/core/transition":                    "state",
	"beacon-chain/db/kv":                              "db",
	"beacon-chain/db/slasherkv":                       "slasherdb",
	"beacon-chain/db/pruner":                          "db-pruner",
	"beacon-chain/rpc/core":                           "rpc/core",
	"beacon-chain/rpc/silaapi/beacon":                     "rpc/beacon",
	"beacon-chain/rpc/silaapi/validator":                  "beacon-api",
	"beacon-chain/rpc/sila/v1alpha1/beacon":          "rpc",
	"beacon-chain/rpc/sila/v1alpha1/validator":       "rpc/validator",
	"beacon-chain/sync/checkpoint":                    "checkpoint-sync",
	"config/features":                                 "flags",
	"proto/sila/v1alpha1":                            "protobuf",
	"validator/db/kv":                                 "db",
	"validator/db/filesystem":                         "db",
	"validator/keymanager/derived":                    "derived-keymanager",
	"validator/keymanager/local":                      "local-keymanager",
	"validator/keymanager/remote-web3signer":          "remote-keymanager",
	"validator/keymanager/remote-web3signer/internal": "remote-keymanager-internal",
	"beacon-chain/forkchoice/doubly-linked-tree":      "forkchoice-doublylinkedtree",
}
